config/routes.rb
Rails.application.routes.draw do

  get 'item/list'

  get 'item/show'

  root to: 'home#index'

  get '/send_mail', to: 'home#send_mail'
  get '/contacts', to: 'home#contacts'
  get '/info', to: 'home#info'

  get '/items/:type', to: 'items#list', as: 'items_list'
  resources :items, only: [:show]

  resources :cart
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contacts
  end

  def info
  end

  def send_mail
  	if params[:letter]
      Info.send_mail(params[:letter][:name], params[:letter][:email], params[:letter][:body])
      flash[:success] = 'Ваше письмо отправлено! Мы скоро с Вами свяжемся!'
  	  redirect_to root_path
    else
      flash[:danger] = 'Письмо не отправлено! Проверьте правильность указанных данных.'
      render :index
    end
  end

  def validate_letter_params(letter_params)
    letter_params.each do |attribute|
       
    end
  end

  def email?
    /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/.match self
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def list
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def panel_is_active?(url)
  	if (request.env['REQUEST_PATH'] == url) || (controller == 'cart')
  	  'active'
  	end
  end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/cart/index.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

app/views/home/contacts.html.erb
<h1>Home#contacts</h1>
<p>Find me in app/views/home/contacts.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<button class="btn btn-primary">click me!</button>

app/views/home/info.html.erb
<h1>Home#info</h1>
<p>Find me in app/views/home/info.html.erb</p>

app/views/info/send_mail.html.erb
<p style="font-size: 20px; color: #585151;">Сообщение оправлено с <%= link_to "o-lyalya.com", "http://o-lyalya.com", style: "font-size: 20px;" %>.</p>
<hr/>

<p style="font-size: 20px; color: #585151;">Письмо от пользователя <%= @name %></p>
<p style="font-size: 20px; color: #585151;"><%= @body %></p>
<p style="font-size: 20px; color: #585151;">Ответ прошу отправить на <%= @email %></p>

app/views/item/list.html.erb
<h1>Item#list</h1>
<p>Find me in app/views/item/list.html.erb</p>

app/views/item/show.html.erb
<h1>Item#show</h1>
<p>Find me in app/views/item/show.html.erb</p>

app/views/layouts/_flash_message.html.erb
<% if flash.any? %>
  <div class="col-md-12">
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= msg %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div id="header">
  <div class="row">
    <div class="logo col-md-6">
      <div class="col-md-6">
        <%= link_to image_tag('logo.png', width: '100%', height: '100%'), root_path %>
      </div>
      <div class="col-md-6">
        <p>Магазин детской одежды и ручных изделий</p>
      </div>
    </div>
    <div class="connection col-md-6">
      <div class="col-md-6 text-center">
        <p class="title">КОНТАКТНЫЕ ТЕЛЕФОНЫ</p>
        <ul>
          <!-- TODO: номера админа -->
          <li>+38(093) 977 14 88</li>
          <li>+38(093) 977 14 48</li>
          <li>+38(093) 977 34 88</li>
        </ul>
        <!-- TODO: модальное окно -->
        <p class="title">
          <%= link_to '#send_letter', 'data-toggle' => 'modal', 'data-target' => '#send_letter' do %>
            НАПИСАТЬ НАМ ПИСЬМО
          <% end %>
        </p>
        <%= render 'layouts/letter_form' %>
      </div>
      <div class="networks col-md-6 text-center">
        <p class="title">МЫ В СОЦСЕТЯХ</p>
        <ul>
          <li><%= link_to '', 'https://www.facebook.com/Olyalya.Online.Store', class: 'fb' %></li>
          <li><%= link_to '', 'https://vk.com/olyalya_store', class: 'vk' %></li>
          <li><%= link_to '', 'https://instagram.com/olyalya_store', class: 'instagram' %></li>
        </ul>
      </div>
    </div>
  </div>
  <br>
  
  <div class="row">
    <%= render 'layouts/flash_message' %>
  </div>
  
  <div class="row">
    <div class="col-md-12">
      <div class="navigation">
        <ul>
          <li class="<%= panel_is_active?('/') %>">
            <%= link_to 'Главная', root_path %>
          </li>
          <li class="<%= panel_is_active?('/info') %>">
            <%= link_to 'Доставка и оплата', info_path %>
          </li>
          <li class="<%= panel_is_active?('/contacts') %>">
            <%= link_to 'Контакты', contacts_path %>
          </li>
          <li class="cart pull-right <%= panel_is_active?('/cart') %>">
            <%= link_to 'Корзина', cart_index_path %>
            <div class="items-amount pull-right">
              <%# Cart.items_amount(session[:list]) %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_letter_form.html.erb
<div class="modal fade" id="send_letter" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">НАПИСАТЬ ПИСЬМО</h4>
      </div>
      <div class="modal-body text-left">
        <%= form_for :letter, url: send_mail_path, html: { id: 'send_mail' }, method: :get do |f| %>
          <div class="field">
            <label for="letter_name" class="pull-left">Ваше имя <span class="red">*</span></label>
            <%= f.text_field :name %>
          </div>

          <div class="field">
            <label for="letter_email" class="pull-left">Ваш электронный адрес <span class="red">*</span></label>
            <%= f.text_field :email %>
          </div>

          <div class="field">
            <label for="letter_body" class="pull-left">Текст письма <span class="red">*</span></label>
            <%= f.text_area  :body %>
          </div>

          <div class="field text-right">
            <%= f.submit 'Отправить', class: 'btn btn-info' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("form#send_mail").validate({
    rules: {
      "letter[name]": "required",
      "letter[email]": { 
        required: true,
        email: true
      },
      "letter[body]": "required"
    },
    messages: {
      "letter[name]": "* Введите имя",
      "letter[email]": { 
        required: "* Введите электронный адрес",
        email: "* Неверный формат"
      },
      "letter[body]": "* Введите текст письма"
    },
    submitHandler: function(form) {
      form.submit();
    }
  });
</script>

app/views/layouts/_side_bar.html.erb
<div class="side_menu">
  <ul>
    <li class="header">Перейти к разделу</li>
    <% Category.all.each do |category| %>
      <%= link_to items_list_path(category.mark) do %>
        <li class="menu <% if params[:item_type] == category.mark %>active<% end %>"><%= category.name %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Olalashop</title>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js' %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="col-md-10 col-md-offset-1">
    <%= render 'layouts/header' %>

    <div id="main">
      <div class="row">
        <div class="col-md-3">
          <%= render 'layouts/side_bar' %>
        </div>
        <div class="col-md-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>